apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: kubernaut-operator
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
      app.kubernetes.io/name: kubernaut-operator
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
        app.kubernetes.io/name: kubernaut-operator
    spec:
      # TODO(user): Uncomment the following code to configure the nodeAffinity expression
      # according to the platforms which are supported by your solution.
      # It is considered best practice to support multiple architectures. You can
      # build your manager image using the makefile target docker-buildx.
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #         - matchExpressions:
      #           - key: kubernetes.io/arch
      #             operator: In
      #             values:
      #               - amd64
      #               - arm64
      #               - ppc64le
      #               - s390x
      #           - key: kubernetes.io/os
      #             operator: In
      #             values:
      #               - linux
      securityContext:
        # Projects are configured by default to adhere to the "restricted" Pod Security Standards.
        # This ensures that deployments meet the highest security requirements for Kubernetes.
        # For more details, see: https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - command:
        - /manager
        args:
          - --leader-elect
          - --health-probe-bind-address=:8081
        image: controller:latest
        name: manager
        env:
        - name: RELATED_IMAGE_GATEWAY
          value: quay.io/kubernaut-ai/gateway@sha256:a38a1819438a1d1404e6621db509d3a1ef8d0cb51f97e8a215da91ababafcc68
        - name: RELATED_IMAGE_DATA_STORAGE
          value: quay.io/kubernaut-ai/datastorage@sha256:5d39ab522a69e4b15a2df735d540d88b99a0848c0da43d44cf94ae6690ca1fff
        - name: RELATED_IMAGE_AIANALYSIS
          value: quay.io/kubernaut-ai/aianalysis@sha256:5c4dd02e03a93f73dc8042972a4cd125b8466b97064195a26e3253c24989389c
        - name: RELATED_IMAGE_SIGNALPROCESSING
          value: quay.io/kubernaut-ai/signalprocessing@sha256:19054b0925dc84d35348007dde25417887dfb13bb531a27f831baba8c4d4d4ca
        - name: RELATED_IMAGE_REMEDIATIONORCHESTRATOR
          value: quay.io/kubernaut-ai/remediationorchestrator@sha256:c1f7860986508382704a9002caa812291229912153735a4f35fcfeef04ca76b4
        - name: RELATED_IMAGE_WORKFLOWEXECUTION
          value: quay.io/kubernaut-ai/workflowexecution@sha256:d9d51e14cfc324dcc45c43f6687ba27eaf6acc1841b18ace449ec5df8c247b05
        - name: RELATED_IMAGE_EFFECTIVENESSMONITOR
          value: quay.io/kubernaut-ai/effectivenessmonitor@sha256:37bc4da52ab36c942894ab858653fa2fb5f97e4dcd66988c359803f4fe5553f0
        - name: RELATED_IMAGE_NOTIFICATION
          value: quay.io/kubernaut-ai/notification@sha256:99d41dae1dc624ab8fe1dbbb4c854a6b63a649a54694a381a4d0568a66bdde23
        - name: RELATED_IMAGE_KUBERNAUT_AGENT
          value: quay.io/kubernaut-ai/kubernautagent@sha256:4cfaee333eaed6403a92c1bc4efd1eb61d40ad5133d2d039846a29f6940a372f
        - name: RELATED_IMAGE_AUTHWEBHOOK
          value: quay.io/kubernaut-ai/authwebhook@sha256:c64853813b7821acb9bd94f254751fc1cc42710545519a4896b9ff0c30b0a2c6
        - name: RELATED_IMAGE_API_FRONTEND
          value: quay.io/kubernaut-ai/apifrontend@sha256:8f566f469f0093ae0e06fa09b3b19898cf73ca03aa71a0652bd17856e8010d85
        - name: RELATED_IMAGE_DB_MIGRATE
          value: quay.io/kubernaut-ai/db-migrate@sha256:e5a3ac560e3b76368151d56dfb4fcfb406eca274df2326d82320516367064fba
        - name: RELATED_IMAGE_CONSOLE
          value: quay.io/kubernaut-ai/kubernaut-console@sha256:db0762d30849b080633c1b8dacc67c45338cd2233a9634697c8bc564611927e5
        - name: RELATED_IMAGE_OAUTH2_PROXY
          value: quay.io/oauth2-proxy/oauth2-proxy@sha256:37c1570c0427e02fc7c947ef2c04e8995b8347b7abc9fcf1dbb4e376a4b221a7
        - name: RELATED_IMAGE_INIT_POSTGRES
          value: registry.redhat.io/rhel10/postgresql-16@sha256:877ac0f8207ada1559ef73b70e92616255b95d3b6ef6a1af314c0f67edfde96e
        - name: RELATED_IMAGE_INIT_UBI_MINIMAL
          value: registry.access.redhat.com/ubi10/ubi-minimal@sha256:7dc60d7777e010c50f5e041ff069112b379c3d5eef2823d20871c67cf663f10c
        ports: []
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        # TODO(user): Configure the resources accordingly based on the project requirements.
        # More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 128Mi
        volumeMounts: []
      volumes: []
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
