apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: kubernaut-operator
    app.kubernetes.io/managed-by: kustomize
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: kubernaut-operator
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
      app.kubernetes.io/name: kubernaut-operator
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
        app.kubernetes.io/name: kubernaut-operator
    spec:
      # TODO(user): Uncomment the following code to configure the nodeAffinity expression
      # according to the platforms which are supported by your solution.
      # It is considered best practice to support multiple architectures. You can
      # build your manager image using the makefile target docker-buildx.
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #         - matchExpressions:
      #           - key: kubernetes.io/arch
      #             operator: In
      #             values:
      #               - amd64
      #               - arm64
      #               - ppc64le
      #               - s390x
      #           - key: kubernetes.io/os
      #             operator: In
      #             values:
      #               - linux
      securityContext:
        # Projects are configured by default to adhere to the "restricted" Pod Security Standards.
        # This ensures that deployments meet the highest security requirements for Kubernetes.
        # For more details, see: https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - command:
        - /manager
        args:
          - --leader-elect
          - --health-probe-bind-address=:8081
        image: controller:latest
        name: manager
        env:
        - name: RELATED_IMAGE_GATEWAY
          value: ghcr.io/jordigilh/kubernaut/gateway@sha256:e69fe00ad22a2ff1e7a07b222a91aa37be9135cd30848b9de126e7291965123e
        - name: RELATED_IMAGE_DATA_STORAGE
          value: ghcr.io/jordigilh/kubernaut/datastorage@sha256:04a52264cd959e0193990c515801b6090112d43969061b6b2c79158605c54881
        - name: RELATED_IMAGE_AIANALYSIS
          value: ghcr.io/jordigilh/kubernaut/aianalysis@sha256:2bd4867e65ed326b463823141b6fea5486c4095823aee1eda851eea6ba1c78cb
        - name: RELATED_IMAGE_SIGNALPROCESSING
          value: ghcr.io/jordigilh/kubernaut/signalprocessing@sha256:d7724a4eedb4078681fb987bfed443d84529aa0df0d30bc136ce86b66825260f
        - name: RELATED_IMAGE_REMEDIATIONORCHESTRATOR
          value: ghcr.io/jordigilh/kubernaut/remediationorchestrator@sha256:e4b0ef575f8878e7ce560a2ed59b9c836b0188271db22668ac5195608a80d5d8
        - name: RELATED_IMAGE_WORKFLOWEXECUTION
          value: ghcr.io/jordigilh/kubernaut/workflowexecution@sha256:386ece6f44ba1744606068145eefb77e1add256cc6afe45e3dfb3a7033940257
        - name: RELATED_IMAGE_EFFECTIVENESSMONITOR
          value: ghcr.io/jordigilh/kubernaut/effectivenessmonitor@sha256:c043adec4acad97480fbfa07d13dd28e9c042c6a9f9c61e4d3594609ad707f59
        - name: RELATED_IMAGE_NOTIFICATION
          value: ghcr.io/jordigilh/kubernaut/notification@sha256:d89b2ec5817d5d945731d40d0aa57731839912a9a750f0e4626e3f0fe64fffba
        - name: RELATED_IMAGE_KUBERNAUT_AGENT
          value: ghcr.io/jordigilh/kubernaut/kubernautagent@sha256:fee18b27537875da6ed9274a40ae3cd2b940e423da63524e9891a052d4670144
        - name: RELATED_IMAGE_AUTHWEBHOOK
          value: ghcr.io/jordigilh/kubernaut/authwebhook@sha256:bdade0e8b959c7894ec7581e560f130400e9c299551c544d6cec8018062f1c18
        - name: RELATED_IMAGE_API_FRONTEND
          value: ghcr.io/jordigilh/kubernaut/apifrontend@sha256:b50a62a008948753c008b1a069e254f23c9be9206d35ba3b9bdc0203ab6d810d
        - name: RELATED_IMAGE_DB_MIGRATE
          value: ghcr.io/jordigilh/kubernaut/db-migrate@sha256:9b729ad2ce9b0f47e203f6179a2b935483cd784c13756a0d5f82f552dab26f87
        - name: RELATED_IMAGE_INIT_POSTGRES
          value: registry.redhat.io/rhel10/postgresql-16@sha256:6626034c7e8a171610212a220efd417eb5ab7792b5dbd912d38976ffe0627301
        - name: RELATED_IMAGE_INIT_UBI_MINIMAL
          value: registry.access.redhat.com/ubi10/ubi-minimal@sha256:2a4785f399dc7ae2f3ca85f68bac0ccac47f3e73464a47c21e4f7ae46b55a053
        ports: []
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        # TODO(user): Configure the resources accordingly based on the project requirements.
        # More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 128Mi
        volumeMounts: []
      volumes: []
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
