apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: kubernaut-operator
    app.kubernetes.io/managed-by: kustomize
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: kubernaut-operator
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
      app.kubernetes.io/name: kubernaut-operator
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
        app.kubernetes.io/name: kubernaut-operator
    spec:
      # TODO(user): Uncomment the following code to configure the nodeAffinity expression
      # according to the platforms which are supported by your solution.
      # It is considered best practice to support multiple architectures. You can
      # build your manager image using the makefile target docker-buildx.
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #         - matchExpressions:
      #           - key: kubernetes.io/arch
      #             operator: In
      #             values:
      #               - amd64
      #               - arm64
      #               - ppc64le
      #               - s390x
      #           - key: kubernetes.io/os
      #             operator: In
      #             values:
      #               - linux
      securityContext:
        # Projects are configured by default to adhere to the "restricted" Pod Security Standards.
        # This ensures that deployments meet the highest security requirements for Kubernetes.
        # For more details, see: https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - command:
        - /manager
        args:
          - --leader-elect
          - --health-probe-bind-address=:8081
        image: controller:latest
        name: manager
        env:
        - name: RELATED_IMAGE_GATEWAY
          value: ghcr.io/jordigilh/kubernaut/gateway@sha256:2ccd68321587f698eda546b6b8b986a591db7d76e2464335974e30ad9099b542
        - name: RELATED_IMAGE_DATA_STORAGE
          value: ghcr.io/jordigilh/kubernaut/datastorage@sha256:60c5004c27a9254844c7c4c77dac8df70657e4201f577a031c58c890587e127a
        - name: RELATED_IMAGE_AIANALYSIS
          value: ghcr.io/jordigilh/kubernaut/aianalysis@sha256:860859ebc56ca923520ef3f96f6c97769426fd6b415b8c8f9d94ae0e47892cc2
        - name: RELATED_IMAGE_SIGNALPROCESSING
          value: ghcr.io/jordigilh/kubernaut/signalprocessing@sha256:c229e240ea49bc5af54c7686e2587960147cbd4de6d2b835360d03b7e29340d2
        - name: RELATED_IMAGE_REMEDIATIONORCHESTRATOR
          value: ghcr.io/jordigilh/kubernaut/remediationorchestrator@sha256:4beb95c6847616f0d7623d42a22b68ccd66dd115d3df3231fade4294e74508df
        - name: RELATED_IMAGE_WORKFLOWEXECUTION
          value: ghcr.io/jordigilh/kubernaut/workflowexecution@sha256:ff4e292938b6fd6c152af59eff412584705e9fb292a80b5ad51c69cf1e8d8dcf
        - name: RELATED_IMAGE_EFFECTIVENESSMONITOR
          value: ghcr.io/jordigilh/kubernaut/effectivenessmonitor@sha256:f75938a934127abac3febdfc02cc7a13bf10f2ff8c81c51c443f20323a1e355c
        - name: RELATED_IMAGE_NOTIFICATION
          value: ghcr.io/jordigilh/kubernaut/notification@sha256:1c5db80aef664d12a74552857146a9cfcb5ecb71f5e37366b33b6a647867f9a1
        - name: RELATED_IMAGE_KUBERNAUT_AGENT
          value: ghcr.io/jordigilh/kubernaut/kubernautagent@sha256:f721baa0b0d19946c228e06a5ef780bc4eaebfaf4be2abd4ecb4369a4ac7a972
        - name: RELATED_IMAGE_AUTHWEBHOOK
          value: ghcr.io/jordigilh/kubernaut/authwebhook@sha256:82a5d311cf3b36d00d95fffa04ab7a540f755862b6dd35ad5926945062e6e9e0
        - name: RELATED_IMAGE_API_FRONTEND
          value: ghcr.io/jordigilh/kubernaut/apifrontend@sha256:a09d77fc10aa7b13cea605dfed2dc9b9c029d5759ef50fe8f94506428fac7d9c
        - name: RELATED_IMAGE_DB_MIGRATE
          value: ghcr.io/jordigilh/kubernaut/db-migrate@sha256:e8846b544b630ab83a74206d0515b856c9a40d2bdc9c56662e14901131c1982a
        - name: RELATED_IMAGE_INIT_POSTGRES
          value: registry.redhat.io/rhel10/postgresql-16@sha256:6626034c7e8a171610212a220efd417eb5ab7792b5dbd912d38976ffe0627301
        - name: RELATED_IMAGE_INIT_UBI_MINIMAL
          value: registry.access.redhat.com/ubi10/ubi-minimal@sha256:2a4785f399dc7ae2f3ca85f68bac0ccac47f3e73464a47c21e4f7ae46b55a053
        ports: []
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        # TODO(user): Configure the resources accordingly based on the project requirements.
        # More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 128Mi
        volumeMounts: []
      volumes: []
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
