//go:build !ignore_autogenerated

/*
Copyright 2026 Jordi Gil.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIAnalysisSpec) DeepCopyInto(out *AIAnalysisSpec) {
	*out = *in
	out.Policy = in.Policy
	out.Logging = in.Logging
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIAnalysisSpec.
func (in *AIAnalysisSpec) DeepCopy() *AIAnalysisSpec {
	if in == nil {
		return nil
	}
	out := new(AIAnalysisSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlignmentCheckLLMSpec) DeepCopyInto(out *AlignmentCheckLLMSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlignmentCheckLLMSpec.
func (in *AlignmentCheckLLMSpec) DeepCopy() *AlignmentCheckLLMSpec {
	if in == nil {
		return nil
	}
	out := new(AlignmentCheckLLMSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlignmentCheckSpec) DeepCopyInto(out *AlignmentCheckSpec) {
	*out = *in
	if in.LLM != nil {
		in, out := &in.LLM, &out.LLM
		*out = new(AlignmentCheckLLMSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlignmentCheckSpec.
func (in *AlignmentCheckSpec) DeepCopy() *AlignmentCheckSpec {
	if in == nil {
		return nil
	}
	out := new(AlignmentCheckSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnomalySpec) DeepCopyInto(out *AnomalySpec) {
	*out = *in
	if in.MaxToolCallsPerTool != nil {
		in, out := &in.MaxToolCallsPerTool, &out.MaxToolCallsPerTool
		*out = new(int)
		**out = **in
	}
	if in.MaxTotalToolCalls != nil {
		in, out := &in.MaxTotalToolCalls, &out.MaxTotalToolCalls
		*out = new(int)
		**out = **in
	}
	if in.MaxRepeatedFailures != nil {
		in, out := &in.MaxRepeatedFailures, &out.MaxRepeatedFailures
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnomalySpec.
func (in *AnomalySpec) DeepCopy() *AnomalySpec {
	if in == nil {
		return nil
	}
	out := new(AnomalySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnsibleSpec) DeepCopyInto(out *AnsibleSpec) {
	*out = *in
	if in.TokenSecretRef != nil {
		in, out := &in.TokenSecretRef, &out.TokenSecretRef
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.CACertSecretRef != nil {
		in, out := &in.CACertSecretRef, &out.CACertSecretRef
		*out = new(CACertSecretRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnsibleSpec.
func (in *AnsibleSpec) DeepCopy() *AnsibleSpec {
	if in == nil {
		return nil
	}
	out := new(AnsibleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditSpec) DeepCopyInto(out *AuditSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditSpec.
func (in *AuditSpec) DeepCopy() *AuditSpec {
	if in == nil {
		return nil
	}
	out := new(AuditSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthWebhookSpec) DeepCopyInto(out *AuthWebhookSpec) {
	*out = *in
	out.Logging = in.Logging
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthWebhookSpec.
func (in *AuthWebhookSpec) DeepCopy() *AuthWebhookSpec {
	if in == nil {
		return nil
	}
	out := new(AuthWebhookSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CACertSecretRef) DeepCopyInto(out *CACertSecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CACertSecretRef.
func (in *CACertSecretRef) DeepCopy() *CACertSecretRef {
	if in == nil {
		return nil
	}
	out := new(CACertSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapRef) DeepCopyInto(out *ConfigMapRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapRef.
func (in *ConfigMapRef) DeepCopy() *ConfigMapRef {
	if in == nil {
		return nil
	}
	out := new(ConfigMapRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataStorageSpec) DeepCopyInto(out *DataStorageSpec) {
	*out = *in
	out.Logging = in.Logging
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataStorageSpec.
func (in *DataStorageSpec) DeepCopy() *DataStorageSpec {
	if in == nil {
		return nil
	}
	out := new(DataStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EMAssessmentSpec) DeepCopyInto(out *EMAssessmentSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EMAssessmentSpec.
func (in *EMAssessmentSpec) DeepCopy() *EMAssessmentSpec {
	if in == nil {
		return nil
	}
	out := new(EMAssessmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EffectivenessMonitorSpec) DeepCopyInto(out *EffectivenessMonitorSpec) {
	*out = *in
	out.Assessment = in.Assessment
	out.Logging = in.Logging
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EffectivenessMonitorSpec.
func (in *EffectivenessMonitorSpec) DeepCopy() *EffectivenessMonitorSpec {
	if in == nil {
		return nil
	}
	out := new(EffectivenessMonitorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayConfigSpec) DeepCopyInto(out *GatewayConfigSpec) {
	*out = *in
	if in.TrustedProxyCIDRs != nil {
		in, out := &in.TrustedProxyCIDRs, &out.TrustedProxyCIDRs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayConfigSpec.
func (in *GatewayConfigSpec) DeepCopy() *GatewayConfigSpec {
	if in == nil {
		return nil
	}
	out := new(GatewayConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewaySpec) DeepCopyInto(out *GatewaySpec) {
	*out = *in
	in.Route.DeepCopyInto(&out.Route)
	in.Config.DeepCopyInto(&out.Config)
	out.Logging = in.Logging
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewaySpec.
func (in *GatewaySpec) DeepCopy() *GatewaySpec {
	if in == nil {
		return nil
	}
	out := new(GatewaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageSpec) DeepCopyInto(out *ImageSpec) {
	*out = *in
	if in.PullSecrets != nil {
		in, out := &in.PullSecrets, &out.PullSecrets
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.Overrides != nil {
		in, out := &in.Overrides, &out.Overrides
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageSpec.
func (in *ImageSpec) DeepCopy() *ImageSpec {
	if in == nil {
		return nil
	}
	out := new(ImageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Kubernaut) DeepCopyInto(out *Kubernaut) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Kubernaut.
func (in *Kubernaut) DeepCopy() *Kubernaut {
	if in == nil {
		return nil
	}
	out := new(Kubernaut)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Kubernaut) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernautAgentSpec) DeepCopyInto(out *KubernautAgentSpec) {
	*out = *in
	in.LLM.DeepCopyInto(&out.LLM)
	out.Session = in.Session
	in.Audit.DeepCopyInto(&out.Audit)
	in.AlignmentCheck.DeepCopyInto(&out.AlignmentCheck)
	out.Summarizer = in.Summarizer
	in.Safety.DeepCopyInto(&out.Safety)
	if in.AdditionalClusterRoleBindings != nil {
		in, out := &in.AdditionalClusterRoleBindings, &out.AdditionalClusterRoleBindings
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Logging = in.Logging
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernautAgentSpec.
func (in *KubernautAgentSpec) DeepCopy() *KubernautAgentSpec {
	if in == nil {
		return nil
	}
	out := new(KubernautAgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernautList) DeepCopyInto(out *KubernautList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Kubernaut, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernautList.
func (in *KubernautList) DeepCopy() *KubernautList {
	if in == nil {
		return nil
	}
	out := new(KubernautList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubernautList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernautSpec) DeepCopyInto(out *KubernautSpec) {
	*out = *in
	in.Image.DeepCopyInto(&out.Image)
	out.PostgreSQL = in.PostgreSQL
	out.Valkey = in.Valkey
	in.Ansible.DeepCopyInto(&out.Ansible)
	in.Monitoring.DeepCopyInto(&out.Monitoring)
	in.Notification.DeepCopyInto(&out.Notification)
	in.AIAnalysis.DeepCopyInto(&out.AIAnalysis)
	in.SignalProcessing.DeepCopyInto(&out.SignalProcessing)
	in.RemediationOrchestrator.DeepCopyInto(&out.RemediationOrchestrator)
	in.WorkflowExecution.DeepCopyInto(&out.WorkflowExecution)
	in.EffectivenessMonitor.DeepCopyInto(&out.EffectivenessMonitor)
	in.KubernautAgent.DeepCopyInto(&out.KubernautAgent)
	in.Gateway.DeepCopyInto(&out.Gateway)
	in.AuthWebhook.DeepCopyInto(&out.AuthWebhook)
	in.DataStorage.DeepCopyInto(&out.DataStorage)
	in.NetworkPolicies.DeepCopyInto(&out.NetworkPolicies)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernautSpec.
func (in *KubernautSpec) DeepCopy() *KubernautSpec {
	if in == nil {
		return nil
	}
	out := new(KubernautSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernautStatus) DeepCopyInto(out *KubernautStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Services != nil {
		in, out := &in.Services, &out.Services
		*out = make([]ServiceStatus, len(*in))
		copy(*out, *in)
	}
	if in.BoundAdditionalClusterRoles != nil {
		in, out := &in.BoundAdditionalClusterRoles, &out.BoundAdditionalClusterRoles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernautStatus.
func (in *KubernautStatus) DeepCopy() *KubernautStatus {
	if in == nil {
		return nil
	}
	out := new(KubernautStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LLMSpec) DeepCopyInto(out *LLMSpec) {
	*out = *in
	if in.MaxRetries != nil {
		in, out := &in.MaxRetries, &out.MaxRetries
		*out = new(int)
		**out = **in
	}
	if in.TimeoutSeconds != nil {
		in, out := &in.TimeoutSeconds, &out.TimeoutSeconds
		*out = new(int)
		**out = **in
	}
	in.OAuth2.DeepCopyInto(&out.OAuth2)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LLMSpec.
func (in *LLMSpec) DeepCopy() *LLMSpec {
	if in == nil {
		return nil
	}
	out := new(LLMSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoggingSpec) DeepCopyInto(out *LoggingSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoggingSpec.
func (in *LoggingSpec) DeepCopy() *LoggingSpec {
	if in == nil {
		return nil
	}
	out := new(LoggingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringSpec) DeepCopyInto(out *MonitoringSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringSpec.
func (in *MonitoringSpec) DeepCopy() *MonitoringSpec {
	if in == nil {
		return nil
	}
	out := new(MonitoringSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkPoliciesSpec) DeepCopyInto(out *NetworkPoliciesSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.GatewayIngressNamespaces != nil {
		in, out := &in.GatewayIngressNamespaces, &out.GatewayIngressNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPoliciesSpec.
func (in *NetworkPoliciesSpec) DeepCopy() *NetworkPoliciesSpec {
	if in == nil {
		return nil
	}
	out := new(NetworkPoliciesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationSpec) DeepCopyInto(out *NotificationSpec) {
	*out = *in
	out.Slack = in.Slack
	if in.Routing != nil {
		in, out := &in.Routing, &out.Routing
		*out = new(ConfigMapRef)
		**out = **in
	}
	out.Logging = in.Logging
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationSpec.
func (in *NotificationSpec) DeepCopy() *NotificationSpec {
	if in == nil {
		return nil
	}
	out := new(NotificationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OAuth2Spec) DeepCopyInto(out *OAuth2Spec) {
	*out = *in
	if in.Scopes != nil {
		in, out := &in.Scopes, &out.Scopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OAuth2Spec.
func (in *OAuth2Spec) DeepCopy() *OAuth2Spec {
	if in == nil {
		return nil
	}
	out := new(OAuth2Spec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyConfigMapRef) DeepCopyInto(out *PolicyConfigMapRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyConfigMapRef.
func (in *PolicyConfigMapRef) DeepCopy() *PolicyConfigMapRef {
	if in == nil {
		return nil
	}
	out := new(PolicyConfigMapRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgreSQLSpec) DeepCopyInto(out *PostgreSQLSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgreSQLSpec.
func (in *PostgreSQLSpec) DeepCopy() *PostgreSQLSpec {
	if in == nil {
		return nil
	}
	out := new(PostgreSQLSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ROAsyncPropagationSpec) DeepCopyInto(out *ROAsyncPropagationSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ROAsyncPropagationSpec.
func (in *ROAsyncPropagationSpec) DeepCopy() *ROAsyncPropagationSpec {
	if in == nil {
		return nil
	}
	out := new(ROAsyncPropagationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ROEffectivenessSpec) DeepCopyInto(out *ROEffectivenessSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ROEffectivenessSpec.
func (in *ROEffectivenessSpec) DeepCopy() *ROEffectivenessSpec {
	if in == nil {
		return nil
	}
	out := new(ROEffectivenessSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RONotificationsSpec) DeepCopyInto(out *RONotificationsSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RONotificationsSpec.
func (in *RONotificationsSpec) DeepCopy() *RONotificationsSpec {
	if in == nil {
		return nil
	}
	out := new(RONotificationsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RORetentionSpec) DeepCopyInto(out *RORetentionSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RORetentionSpec.
func (in *RORetentionSpec) DeepCopy() *RORetentionSpec {
	if in == nil {
		return nil
	}
	out := new(RORetentionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RORoutingSpec) DeepCopyInto(out *RORoutingSpec) {
	*out = *in
	if in.ConsecutiveFailureThreshold != nil {
		in, out := &in.ConsecutiveFailureThreshold, &out.ConsecutiveFailureThreshold
		*out = new(int)
		**out = **in
	}
	if in.ExponentialBackoffMaxExponent != nil {
		in, out := &in.ExponentialBackoffMaxExponent, &out.ExponentialBackoffMaxExponent
		*out = new(int)
		**out = **in
	}
	if in.NoActionRequiredDelayHours != nil {
		in, out := &in.NoActionRequiredDelayHours, &out.NoActionRequiredDelayHours
		*out = new(int)
		**out = **in
	}
	if in.IneffectiveChainThreshold != nil {
		in, out := &in.IneffectiveChainThreshold, &out.IneffectiveChainThreshold
		*out = new(int)
		**out = **in
	}
	if in.RecurrenceCountThreshold != nil {
		in, out := &in.RecurrenceCountThreshold, &out.RecurrenceCountThreshold
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RORoutingSpec.
func (in *RORoutingSpec) DeepCopy() *RORoutingSpec {
	if in == nil {
		return nil
	}
	out := new(RORoutingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ROTimeoutsSpec) DeepCopyInto(out *ROTimeoutsSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ROTimeoutsSpec.
func (in *ROTimeoutsSpec) DeepCopy() *ROTimeoutsSpec {
	if in == nil {
		return nil
	}
	out := new(ROTimeoutsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationOrchestratorSpec) DeepCopyInto(out *RemediationOrchestratorSpec) {
	*out = *in
	out.Timeouts = in.Timeouts
	in.Routing.DeepCopyInto(&out.Routing)
	out.EffectivenessAssessment = in.EffectivenessAssessment
	out.AsyncPropagation = in.AsyncPropagation
	out.Notifications = in.Notifications
	out.Retention = in.Retention
	out.Logging = in.Logging
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationOrchestratorSpec.
func (in *RemediationOrchestratorSpec) DeepCopy() *RemediationOrchestratorSpec {
	if in == nil {
		return nil
	}
	out := new(RemediationOrchestratorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouteSpec) DeepCopyInto(out *RouteSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouteSpec.
func (in *RouteSpec) DeepCopy() *RouteSpec {
	if in == nil {
		return nil
	}
	out := new(RouteSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SafetySpec) DeepCopyInto(out *SafetySpec) {
	*out = *in
	in.Sanitization.DeepCopyInto(&out.Sanitization)
	in.Anomaly.DeepCopyInto(&out.Anomaly)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SafetySpec.
func (in *SafetySpec) DeepCopy() *SafetySpec {
	if in == nil {
		return nil
	}
	out := new(SafetySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SanitizationSpec) DeepCopyInto(out *SanitizationSpec) {
	*out = *in
	if in.InjectionPatternsEnabled != nil {
		in, out := &in.InjectionPatternsEnabled, &out.InjectionPatternsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.CredentialScrubEnabled != nil {
		in, out := &in.CredentialScrubEnabled, &out.CredentialScrubEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SanitizationSpec.
func (in *SanitizationSpec) DeepCopy() *SanitizationSpec {
	if in == nil {
		return nil
	}
	out := new(SanitizationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyRef) DeepCopyInto(out *SecretKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyRef.
func (in *SecretKeyRef) DeepCopy() *SecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(SecretKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceStatus) DeepCopyInto(out *ServiceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceStatus.
func (in *ServiceStatus) DeepCopy() *ServiceStatus {
	if in == nil {
		return nil
	}
	out := new(ServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SessionSpec) DeepCopyInto(out *SessionSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SessionSpec.
func (in *SessionSpec) DeepCopy() *SessionSpec {
	if in == nil {
		return nil
	}
	out := new(SessionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SignalProcessingSpec) DeepCopyInto(out *SignalProcessingSpec) {
	*out = *in
	out.Policy = in.Policy
	if in.ProactiveSignalMappings != nil {
		in, out := &in.ProactiveSignalMappings, &out.ProactiveSignalMappings
		*out = new(ConfigMapRef)
		**out = **in
	}
	out.Logging = in.Logging
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SignalProcessingSpec.
func (in *SignalProcessingSpec) DeepCopy() *SignalProcessingSpec {
	if in == nil {
		return nil
	}
	out := new(SignalProcessingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlackSpec) DeepCopyInto(out *SlackSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlackSpec.
func (in *SlackSpec) DeepCopy() *SlackSpec {
	if in == nil {
		return nil
	}
	out := new(SlackSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SummarizerSpec) DeepCopyInto(out *SummarizerSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SummarizerSpec.
func (in *SummarizerSpec) DeepCopy() *SummarizerSpec {
	if in == nil {
		return nil
	}
	out := new(SummarizerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TektonSpec) DeepCopyInto(out *TektonSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TektonSpec.
func (in *TektonSpec) DeepCopy() *TektonSpec {
	if in == nil {
		return nil
	}
	out := new(TektonSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValkeySpec) DeepCopyInto(out *ValkeySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValkeySpec.
func (in *ValkeySpec) DeepCopy() *ValkeySpec {
	if in == nil {
		return nil
	}
	out := new(ValkeySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkflowExecutionSpec) DeepCopyInto(out *WorkflowExecutionSpec) {
	*out = *in
	in.Tekton.DeepCopyInto(&out.Tekton)
	out.Logging = in.Logging
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkflowExecutionSpec.
func (in *WorkflowExecutionSpec) DeepCopy() *WorkflowExecutionSpec {
	if in == nil {
		return nil
	}
	out := new(WorkflowExecutionSpec)
	in.DeepCopyInto(out)
	return out
}
