apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubernaut-operator-leader-election
  namespace: {{ include "kubernaut-operator.namespace" . }}
  labels:
    {{- include "kubernaut-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubernaut-operator-leader-election
subjects:
  - kind: ServiceAccount
    name: {{ include "kubernaut-operator.serviceAccountName" . }}
    namespace: {{ include "kubernaut-operator.namespace" . }}
