#!/usr/bin/env bash
# generate-imageset.sh — regenerate imageset-config.yaml from manager.yaml
#
# Usage:
#   ./hack/airgap/generate-imageset.sh [VERSION]
#
# VERSION defaults to the VERSION variable in the Makefile.

set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

VERSION="${1:-$(grep '^VERSION' Makefile | head -1 | awk '{print $NF}')}"
MANAGER="config/manager/manager.yaml"
OUT="hack/airgap/imageset-config.yaml"

images=()
while IFS= read -r img; do
  images+=("$img")
done < <(grep 'value:' "$MANAGER" | sed 's/.*value: //' | sort)

cat > "$OUT" <<HEADER
# ImageSetConfiguration for mirroring all Kubernaut images to a disconnected
# OpenShift cluster. Use with oc-mirror v2 (OCP 4.18+).
#
# Auto-generated by hack/airgap/generate-imageset.sh — do not edit manually.
#
# Usage (bastion host with internet access):
#
#   oc-mirror --config hack/airgap/imageset-config.yaml \\
#     docker://<mirror-registry>
#
# Version: v${VERSION}
kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
storageConfig:
  local:
    path: ./kubernaut-mirror
mirror:
  additionalImages:
    # Operator
    - name: quay.io/kubernaut-ai/kubernaut-operator:v${VERSION}
    # Operator bundle
    - name: quay.io/kubernaut-ai/kubernaut-operator-bundle:v${VERSION}
    # Operand and infrastructure images
HEADER

for img in "${images[@]}"; do
  echo "    - name: ${img}" >> "$OUT"
done

echo ""
echo "Generated ${OUT} with $((${#images[@]} + 2)) images for v${VERSION}"
